services:
  app:
    build:
      target: deps
    command: sh -c "npx prisma generate && npm run dev"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./public:/app/public
      - ./next.config.ts:/app/next.config.ts
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
